### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Bilgee** [jackg0h/foodtag#1]
Thank you for sharing your project. 
Where can I download the food dataset?
I searched the dataset, but I could not find it.

**Comment by jackgoh** [comment]
Welcome :) Sorry, currently it's a private dataset. I will try my best to release to public once the paper has been published. 

Btw, the dataset is scraped from instagram and google images, containing 200 images per category. You can build your own dataset too.

**Comment by Bilgee** [comment]
Thank you for replying. 
Good luck with your research paper.
